name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libasound2-dev
      run: sudo apt install -y libasound2-dev
    - name: Install libudev
      run: sudo apt install -y libudev-dev
    - name: Build
      run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
